#!/bin/sh
#
cp ./main.c /usr/src/kernel/
cp ./config.h /usr/src/include/minix/
cp ./proc.h /usr/src/kernel/
cp ./proc.c /usr/src/kernel/
cp ./schedproc.h /usr/src/servers/sched/
cp ./schedule.c /usr/src/servers/sched/

