#!/bin/sh
#
echo Test 6 - Mixed CPU and IO bound tasks
echo The processes should run faster then each run separately
#
echo Running single cpu task:
time ./cpu 2500000 0
echo Running single io task:
time ./io 5000 0
echo Running both concurrently:
time ./cpu 2500000 0 &
time ./io 5000 0 &
