#!/bin/sh
#
echo Test 4 - One IO task with one ticket and three CPU tasks
echo each with 100 tickets.
#
time ./io 5000 -19 &
time ./cpu 1530000000 80 &
time ./cpu 1530000000 80 &
time ./cpu 1530000000 80 &
