#!/bin/sh
#
echo Test 3 - Three CPU bound tasks, with 25, 50, and 100 tickets
echo They should have runtimes of a ration of about 7:10:12
#
time ./cpu 1530000000 5 &
time ./cpu 1530000000 30 &
time ./cpu 1530000000 80 &
