#!/bin/sh
#
cp ./original/unistd.h /usr/src/include/
cp ./original/unistd.h /usr/include/
cp ./original/request.c /usr/src/servers/vfs/request.c
cp ./original/vfsproto.h /usr/src/servers/vfs/proto.h
cp ./original/vfstable.c /usr/src/servers/vfs/table.c
cp ./original/vfsread.c /usr/src/servers/vfs/read.c
cp ./original/vfswrite.c /usr/src/servers/vfs/write.c
cp ./original/mfsproto.h /usr/src/servers/mfs/proto.h
cp ./original/mfstable.c /usr/src/servers/mfs/table.c
cp ./original/mfsread.c /usr/src/servers/mfs/read.c
cp ./original/mfsmain.c /usr/src/servers/mfs/main.c
cp ./original/vfsif.h /usr/src/include/minix/
cp ./original/vfsif.h /usr/include/minix/
cp ./original/callnr.h /usr/src/include/minix/
cp ./original/callnr.h /usr/include/minix/
cp ./original/sysread.c /usr/src/lib/libc/sys-minix/read.c
cp ./original/syswrite.c /usr/src/lib/libc/sys-minix/write.c
