#!/bin/sh
#
cp ./unistd.h /usr/src/include/
cp ./unistd.h /usr/include/
cp ./request.c /usr/src/servers/vfs/request.c
cp ./vfsproto.h /usr/src/servers/vfs/proto.h
cp ./vfstable.c /usr/src/servers/vfs/table.c
cp ./vfsread.c /usr/src/servers/vfs/read.c
cp ./vfswrite.c /usr/src/servers/vfs/write.c
cp ./mfsproto.h /usr/src/servers/mfs/proto.h
cp ./mfstable.c /usr/src/servers/mfs/table.c
cp ./mfsread.c /usr/src/servers/mfs/read.c
cp ./vfsif.h /usr/src/include/minix/
cp ./vfsif.h /usr/include/minix/
cp ./callnr.h /usr/src/include/minix/
cp ./callnr.h /usr/include/minix/
cp ./sysread.c /usr/src/lib/libc/sys-minix/read.c
cp ./syswrite.c /usr/src/lib/libc/sys-minix/write.c
