#!/bin/sh
# Created 6/5/2014
# This script copies “test.txt” to “test2.txt” and verifies that the metadata 
# copied correctly. It then changes the metadata of the original file, reads
# the metadata of the copied file, and verifies that it did not change.
#
# read the metadata from test.txt
output=$(metacat test.txt)
# copy test.txt to test2.txt
cp test.txt test2.txt
# confirm that test.txt's metadata didn't change
output2=$(metacat test.txt)
if [ $output = $output2 ]; then
	# confirm that test2.txt's metadata is the same as test.txt's
	output2=$(metacat test2.txt)
	if [ $output = $output2 ]; then
		# change the metadata of test.txt to "blah blah metad"
		metatag test.txt "blah blah metad"
		# confirm the metadata of test2.txt did not change
		output = $(metacat test2.txt)
		if [ $output = $output2 ]; then
			echo "pass"
			exit 0
		else
			echo "fail"
			exit 1
		fi
	else
		echo "fail"
		exit 1
	fi
else
	echo "fail"
	exit 1
fi
