#!/bin/sh
# Created 6/5/2014
# This script runs du to display the space used on the disk.
# It then creates 1000 files, adds metadata to each of
# them, and then deletes the files. It then runs du again,
# so any difference will be immediately noticeable.
#

echo "running du..."
du

echo "creating files..."
for i in $(seq 1 1000); do
	echo $i > $i
	./metatag $i "metadata"
	rm $i
done

echo "running du..."
du
